### PR TITLE
Wed afternoon

### PR DESCRIPTION
**Pull request by jwileman1**
Completed first parse for dates ... all those edits are in Main branch 
Created a new branch called WedAfternoon- and started on attribute scrub- here are a few edits

### CODE REVIEW

**Review by mattyschell — CHANGES_REQUESTED** [review]
> Digital planimetrics were derived using the imagery products delivered with the 2020 New York Statewide Flyover

should this be 2022?

**Comment by jwileman1** [comment]
Ok… I’ll update… I wasn’t sure if this was a ever 4 year fly where somehow with Covid you got a off year fly…  I'm assuming from your comment that NY does a statewide flyover annually

So... I'll update that date... and probably ought to update the Capture Table that had the history of updates and corresponding imagery... so, the latest is the 2022 capture with 2022 imagery ...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mattyschell** [comment]
Thanks @jwileman1 

The flyovers are typically on even numbered years.  Most recently 2022 with planimetrics delayed a bit and delivered using the latest, 2022.

**Comment by mattyschell** [comment]
Thanks @jwileman1 !

**Pull request merged**
