### PR TITLE
Final edits

### PR DESCRIPTION
**Pull request by jwileman1**
Final edits 'attached' here.  These are the edits for the last few days (Friday, Saturday and Sunday).   I sent a pull request already for edits prior to this timeframe/pull request.  

I was creating branches daily and then I screwed up on Friday and put some edits in a branch called Friday and then put some edits in the Main branch.  Ugh!

So, I merged all my edits into Main  ... and from then on out, I just made changes to Main.  So, all those changes should be in this pull request.

Please merge these in and let me know if you need any edits.  Afterward, I'd like to do a final QC on Next branch to make sure all my edits made it threw (just making sure as I'm still kinda new with github ... pretty sure they did/will, but ...)

### CODE REVIEW

**Comment by timcala37** [comment]
Do you think it makes sense to add a line to the Introduction section something like: "As part of a reorganization of City government agencies, DoITT was renamed as 'Office of Technology & Innovation (OTI)'. DoITT and OTI are equivalent terms for the same city agency."?

The updated metadata feels out of date if it doesn't mention the current name of the agency that owns the data.

**Comment by mattyschell** [comment]
@timcala37 thanks, good idea.  I've filed issue #29 for this

**Comment by mattyschell** [comment]
@jwileman1 can you please review the conflicts and advise?  Thanks

**Comment by mattyschell** [comment]
@jwileman1 or maybe you can't see the conflicts easily since you are not a contributor on the repo? Let me know, no worries.

I think I should resolve in favor of "main" ie you, when in doubt:

image

**Comment by jwileman1** [comment]
OK... I made the changes ... hopefully you 'see' them now?

**Pull request merged**
